import:
  - ~/.alacritty.macos.yml
  - ~/.alacritty.linux.yml

env:
  TERM: alacritty

window:
  dynamic_title: false
  dynamic_padding: true
  padding:
    x: 2
    y: 2

scrolling:
  history: 0

font:
  use_thin_strokes: true
  normal:
    family: "Source Code Pro"

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x000000'
    foreground: '0xe5e5e5'

  cursor:
    text: CellBackground
    cursor: '0xFFFFFF'

  normal:
    black:   '0x000000'
    red:     '0xf82570'
    green:   '0xa6e12d'
    yellow:  '0xe4db73'
    blue:    '0xfc961f'
    magenta: '0xae81ff'
    cyan:    '0x66d9ee'
    white:   '0xfdfff1'

  bright:
    black:   '0x6e7066'
    red:     '0xf82570'
    green:   '0xa6e12d'
    yellow:  '0xe4db73'
    blue:    '0xfc961f'
    magenta: '0xae81ff'
    cyan:    '0x66d9ee'
    white:   '0xffffff'

selection:
  save_to_clipboard: true

cursor:
  unfocused_hollow: true

mouse:
  hide_when_typing: true

key_bindings:
  - { key: Paste,                                      action: Paste         }
  - { key: Copy,                                       action: Copy          }
  - { key: L,         mods: Control,                   chars: "\x0c"         }
  - { key: L,         mods: Control,       mode: ~Vi,  action: None          }
  - { key: PageUp,    mods: Shift,         mode: ~Alt, action: None          }
  - { key: PageDown,  mods: Shift,         mode: ~Alt, action: None          }
  - { key: Home,      mods: Shift,         mode: ~Alt, action: None          }
  - { key: End,       mods: Shift,         mode: ~Alt, action: None          }

  # Vi Mode
  - { key: Space,     mods: Shift|Control, mode: Vi, action: None            }
  - { key: Space,     mods: Shift|Control,           action: None            }
  - { key: Escape,                         mode: Vi, action: None            }
  - { key: I,                              mode: Vi, action: None            }
  - { key: I,                              mode: Vi, action: None            }
  - { key: C,         mods: Control,       mode: Vi, action: None            }
  - { key: Y,         mods: Control,       mode: Vi, action: None            }
  - { key: E,         mods: Control,       mode: Vi, action: None            }
  - { key: G,                              mode: Vi, action: None            }
  - { key: G,         mods: Shift,         mode: Vi, action: None            }
  - { key: B,         mods: Control,       mode: Vi, action: None            }
  - { key: F,         mods: Control,       mode: Vi, action: None            }
  - { key: U,         mods: Control,       mode: Vi, action: None            }
  - { key: D,         mods: Control,       mode: Vi, action: None            }
  - { key: Y,                              mode: Vi, action: None            }
  - { key: Y,                              mode: Vi, action: None            }
  - { key: Copy,                           mode: Vi, action: None            }
  - { key: V,                              mode: Vi, action: None            }
  - { key: V,         mods: Shift,         mode: Vi, action: None            }
  - { key: V,         mods: Control,       mode: Vi, action: None            }
  - { key: V,         mods: Alt,           mode: Vi, action: None            }
  - { key: Return,                         mode: Vi, action: None            }
  - { key: K,                              mode: Vi, action: None            }
  - { key: J,                              mode: Vi, action: None            }
  - { key: H,                              mode: Vi, action: None            }
  - { key: L,                              mode: Vi, action: None            }
  - { key: Up,                             mode: Vi, action: None            }
  - { key: Down,                           mode: Vi, action: None            }
  - { key: Left,                           mode: Vi, action: None            }
  - { key: Right,                          mode: Vi, action: None            }
  - { key: Key0,                           mode: Vi, action: None            }
  - { key: Key4,      mods: Shift,         mode: Vi, action: None            }
  - { key: Key6,      mods: Shift,         mode: Vi, action: None            }
  - { key: H,         mods: Shift,         mode: Vi, action: None            }
  - { key: M,         mods: Shift,         mode: Vi, action: None            }
  - { key: L,         mods: Shift,         mode: Vi, action: None            }
  - { key: B,                              mode: Vi, action: None            }
  - { key: W,                              mode: Vi, action: None            }
  - { key: E,                              mode: Vi, action: None            }
  - { key: B,         mods: Shift,         mode: Vi, action: None            }
  - { key: W,         mods: Shift,         mode: Vi, action: None            }
  - { key: E,         mods: Shift,         mode: Vi, action: None            }
  - { key: Key5,      mods: Shift,         mode: Vi, action: None            }
  - { key: Slash,                          mode: Vi, action: None            }
  - { key: Slash,     mods: Shift,         mode: Vi, action: None            }
  - { key: N,                              mode: Vi, action: None            }
  - { key: N,         mods: Shift,         mode: Vi, action: None            }

  # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control|Shift,           action: None            }
  - { key: C,         mods: Control|Shift,           action: None            }
  - { key: F,         mods: Control|Shift,           action: None            }
  - { key: B,         mods: Control|Shift,           action: None            }
  - { key: C,         mods: Control|Shift, mode: Vi, action: None            }
  - { key: Insert,    mods: Shift,                   action: None            }
  - { key: Key0,      mods: Control,                 action: None            }
  - { key: Equals,    mods: Control,                 action: None            }
  - { key: Plus,      mods: Control,                 action: None            }
  - { key: Minus,     mods: Control,                 action: None            }

  # (Windows only)
  - { key: Return,    mods: Alt,                action: None                 }

  # (macOS only)
  - { key: K,         mods: Command, mode: ~Vi, action: None                 }
  - { key: Key0,      mods: Command,            action: ResetFontSize        }
  - { key: Equals,    mods: Command,            action: IncreaseFontSize     }
  - { key: Plus,      mods: Command,            action: IncreaseFontSize     }
  - { key: Minus,     mods: Command,            action: DecreaseFontSize     }
  - { key: K,         mods: Command,            action: None                 }
  - { key: V,         mods: Command,            action: Paste                }
  - { key: C,         mods: Command,            action: Copy                 }
  - { key: C,         mods: Command, mode: Vi,  action: None                 }
  - { key: H,         mods: Command,            action: None                 }
  - { key: M,         mods: Command,            action: None                 }
  - { key: Q,         mods: Command,            action: None                 }
  - { key: W,         mods: Command,            action: Quit                 }
  - { key: N,         mods: Command,            action: SpawnNewInstance     }
  - { key: F,         mods: Command|Control,    action: None                 }
  - { key: F,         mods: Command,            action: None                 }
  - { key: B,         mods: Command,            action: None                 }

  # Beep patch https://github.com/alacritty/alacritty/issues/3014
  - { key: Slash,     mods: Control,            chars: "\x1f"                }

  # Alt+ fix https://github.com/alacritty/alacritty/issues/62
  - { key: A,         mods: Alt,                chars: "\x1ba"               }
  - { key: B,         mods: Alt,                chars: "\x1bb"               }
  - { key: C,         mods: Alt,                chars: "\x1bc"               }
  - { key: D,         mods: Alt,                chars: "\x1bd"               }
  - { key: E,         mods: Alt,                chars: "\x1be"               }
  - { key: F,         mods: Alt,                chars: "\x1bf"               }
  - { key: G,         mods: Alt,                chars: "\x1bg"               }
  - { key: H,         mods: Alt,                chars: "\x1bh"               }
  - { key: I,         mods: Alt,                chars: "\x1bi"               }
  - { key: J,         mods: Alt,                chars: "\x1bj"               }
  - { key: K,         mods: Alt,                chars: "\x1bk"               }
  - { key: L,         mods: Alt,                chars: "\x1bl"               }
  - { key: M,         mods: Alt,                chars: "\x1bm"               }
  - { key: N,         mods: Alt,                chars: "\x1bn"               }
  - { key: O,         mods: Alt,                chars: "\x1bo"               }
  - { key: P,         mods: Alt,                chars: "\x1bp"               }
  - { key: Q,         mods: Alt,                chars: "\x1bq"               }
  - { key: R,         mods: Alt,                chars: "\x1br"               }
  - { key: S,         mods: Alt,                chars: "\x1bs"               }
  - { key: T,         mods: Alt,                chars: "\x1bt"               }
  - { key: U,         mods: Alt,                chars: "\x1bu"               }
  - { key: V,         mods: Alt,                chars: "\x1bv"               }
  - { key: W,         mods: Alt,                chars: "\x1bw"               }
  - { key: X,         mods: Alt,                chars: "\x1bx"               }
  - { key: Y,         mods: Alt,                chars: "\x1by"               }
  - { key: Z,         mods: Alt,                chars: "\x1bz"               }
  - { key: A,         mods: Alt|Shift,          chars: "\x1bA"               }
  - { key: B,         mods: Alt|Shift,          chars: "\x1bB"               }
  - { key: C,         mods: Alt|Shift,          chars: "\x1bC"               }
  - { key: D,         mods: Alt|Shift,          chars: "\x1bD"               }
  - { key: E,         mods: Alt|Shift,          chars: "\x1bE"               }
  - { key: F,         mods: Alt|Shift,          chars: "\x1bF"               }
  - { key: G,         mods: Alt|Shift,          chars: "\x1bG"               }
  - { key: H,         mods: Alt|Shift,          chars: "\x1bH"               }
  - { key: I,         mods: Alt|Shift,          chars: "\x1bI"               }
  - { key: J,         mods: Alt|Shift,          chars: "\x1bJ"               }
  - { key: K,         mods: Alt|Shift,          chars: "\x1bK"               }
  - { key: L,         mods: Alt|Shift,          chars: "\x1bL"               }
  - { key: M,         mods: Alt|Shift,          chars: "\x1bM"               }
  - { key: N,         mods: Alt|Shift,          chars: "\x1bN"               }
  - { key: O,         mods: Alt|Shift,          chars: "\x1bO"               }
  - { key: P,         mods: Alt|Shift,          chars: "\x1bP"               }
  - { key: Q,         mods: Alt|Shift,          chars: "\x1bQ"               }
  - { key: R,         mods: Alt|Shift,          chars: "\x1bR"               }
  - { key: S,         mods: Alt|Shift,          chars: "\x1bS"               }
  - { key: T,         mods: Alt|Shift,          chars: "\x1bT"               }
  - { key: U,         mods: Alt|Shift,          chars: "\x1bU"               }
  - { key: V,         mods: Alt|Shift,          chars: "\x1bV"               }
  - { key: W,         mods: Alt|Shift,          chars: "\x1bW"               }
  - { key: X,         mods: Alt|Shift,          chars: "\x1bX"               }
  - { key: Y,         mods: Alt|Shift,          chars: "\x1bY"               }
  - { key: Z,         mods: Alt|Shift,          chars: "\x1bZ"               }
  - { key: Key1,      mods: Alt,                chars: "\x1b1"               }
  - { key: Key2,      mods: Alt,                chars: "\x1b2"               }
  - { key: Key3,      mods: Alt,                chars: "\x1b3"               }
  - { key: Key4,      mods: Alt,                chars: "\x1b4"               }
  - { key: Key5,      mods: Alt,                chars: "\x1b5"               }
  - { key: Key6,      mods: Alt,                chars: "\x1b6"               }
  - { key: Key7,      mods: Alt,                chars: "\x1b7"               }
  - { key: Key8,      mods: Alt,                chars: "\x1b8"               }
  - { key: Key9,      mods: Alt,                chars: "\x1b9"               }
  - { key: Key0,      mods: Alt,                chars: "\x1b0"               }
  - { key: Space,     mods: Control,            chars: "\x00"                }
  - { key: Grave,     mods: Alt,                chars: "\x1b`"               }
  - { key: Grave,     mods: Alt|Shift,          chars: "\x1b~"               }
  - { key: Period,    mods: Alt,                chars: "\x1b."               }
  - { key: Key8,      mods: Alt|Shift,          chars: "\x1b*"               }
  - { key: Key3,      mods: Alt|Shift,          chars: "\x1b#"               }
  - { key: Period,    mods: Alt|Shift,          chars: "\x1b>"               }
  - { key: Comma,     mods: Alt|Shift,          chars: "\x1b<"               }
  - { key: Minus,     mods: Alt|Shift,          chars: "\x1b_"               }
  - { key: Key5,      mods: Alt|Shift,          chars: "\x1b%"               }
  - { key: Key6,      mods: Alt|Shift,          chars: "\x1b^"               }
  - { key: Backslash, mods: Alt,                chars: "\x1b\\"              }
  - { key: Backslash, mods: Alt|Shift,          chars: "\x1b|"               }
  - { key: LBracket,  mods: Alt,                chars: "\x1b["               }
  - { key: RBracket,  mods: Alt,                chars: "\x1b]"               }
  - { key: Key6,      mods: Control,            chars: "\x1e"                }
