#!/bin/sh

# cd
# wget -N https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt
# wget -N https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt
# /usr/bin/pkill -HUP dnsmasq
# brew services restart dnsmasq

cd /opt/dnscrypt-proxy
/usr/local/bin/wget -N https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt
